import { initializeApp } from 'https://www.gstatic.com/firebasejs/9.15.0/firebase-app.js';
import { getDatabase, ref, child, get } from 'https://www.gstatic.com/firebasejs/9.15.0/firebase-database.js';

// Config generated by the Firebase Platform
const firebaseConfig = {
    apiKey: "AIzaSyBUO4-CRJphTwClUQRQCofWDi15KlHV8qw",
    authDomain: "tabularasa-db9e6.firebaseapp.com",
    projectId: "tabularasa-db9e6",
    storageBucket: "tabularasa-db9e6.appspot.com",
    messagingSenderId: "197821455165",
    appId: "1:197821455165:web:37b316c69084f905ac4354",
    measurementId: "G-P85WQQB29B",
    databaseURL: "https://tabularasa-db9e6-default-rtdb.firebaseio.com/"
  };

const app = initializeApp(firebaseConfig);
const dbRef = ref(getDatabase(app));

get(dbRef).then((snapshot) => {
  if (snapshot.exists()) {
    parseSnapshot(snapshot)
  } else {
    console.log("No data available");
  }
}).catch((error) => {
  console.error(error);
});

function parseSnapshot(snapshot){
    Object.keys(snapshot.val()).forEach((key, value) =>{
        document.getElementById('container').appendChild(document.createTextNode(' |'+value + ': ' + String(key)))
    })  
}

