
//var firebase = require('firebase')

import { initializeApp } from 'firebase/app';
import { getDatabase, ref, child, get } from 'firebase/database';
import {getAuth, createUserWithEmailAndPassword, signInWithEmailAndPassword} from "firebase/auth"
//import {firebaseui} from 'firebaseui';


var firebaseui = require('firebaseui')

// Config generated by the Firebase Platform
const firebaseConfig = {
    apiKey: "AIzaSyBUO4-CRJphTwClUQRQCofWDi15KlHV8qw",
    authDomain: "tabularasa-db9e6.firebaseapp.com",
    projectId: "tabularasa-db9e6",
    storageBucket: "tabularasa-db9e6.appspot.com",
    messagingSenderId: "197821455165",
    appId: "1:197821455165:web:37b316c69084f905ac4354",
    measurementId: "G-P85WQQB29B",
    databaseURL: "https://tabularasa-db9e6-default-rtdb.firebaseio.com/"
  };

const app = initializeApp(firebaseConfig);
const dbRef = ref(getDatabase(app));
const auth = getAuth(app);

$('#signupSubmit').on('click', ()=>{
  let email = $('#signupEmail').val()
  let password = $('#signupPassword').val();
  console.log(email, password)
  createUserWithEmailAndPassword(auth, email, password)
  .then((userCredential) => {
    // Signed in 
    const user = userCredential.user;
    console.log('you made an account as ' + user)
    // ...
  })
  .catch((error) => {
    const errorCode = error.code;
    const errorMessage = error.message;
    // ..
  });
})
$('#signinSubmit').on('click', ()=>{
  let email = $('#signinEmail').val()
  let password = $('#signinPassword').val();
  console.log(email, password)
  signInWithEmailAndPassword(auth, email, password)
  .then((userCredential) => {
    // Signed in 
    const user = userCredential.user;
    console.log('you logged into an account as ' + user)
    // ...
  })
  .catch((error) => {
    const errorCode = error.code;
    const errorMessage = error.message;
    // ..
  });

})



