
//var firebase = require('firebase')

import { initializeApp } from 'firebase/app';
import { getDatabase, ref, child, get } from 'firebase/database';
import {getAuth, createUserWithEmailAndPassword, signInWithEmailAndPassword} from "firebase/auth"
var firebaseui = require('firebaseui')

// Config generated by the Firebase Platform
const firebaseConfig = {
    apiKey: "AIzaSyBUO4-CRJphTwClUQRQCofWDi15KlHV8qw",
    authDomain: "tabularasa-db9e6.firebaseapp.com",
    projectId: "tabularasa-db9e6",
    storageBucket: "tabularasa-db9e6.appspot.com",
    messagingSenderId: "197821455165",
    appId: "1:197821455165:web:37b316c69084f905ac4354",
    measurementId: "G-P85WQQB29B",
    databaseURL: "https://tabularasa-db9e6-default-rtdb.firebaseio.com/"
  };

const app = initializeApp(firebaseConfig);
const dbRef = ref(getDatabase(app));
const auth = getAuth(app);

//sign Up
$('#signupSubmit').on('click', ()=>{
  createUserWithEmailAndPassword(auth, $('#signupEmail').val(), $('#signupPassword').val())
  .then((userCredential) => {
      // Signed in 
      const user = userCredential.user;
      $('#signup').toggle()
      $('#signin').toggle()
      $('#statusContainer').html('You have created an Account')
  })
  .catch((error) => {
      const errorCode = error.code;
      const errorMessage = error.message;
  });
})

//sign in
$('#signinSubmit').on('click', ()=>{
  signInWithEmailAndPassword(auth, $('#signinEmail').val(), $('#signinPassword').val())
  .then((userCredential) => {
      const user = userCredential.user;
      $('#signin').toggle()
      $('#statusContainer').html('You have been logged in')
  })
  .catch((error) => {
      const errorCode = error.code;
      const errorMessage = error.message;
      console.log(error.message)
  });
})

$('#haveAccount').on('click', ()=>{
  $('#signin').toggle();
  $('#signup').toggle();
})

$('#createAccount').on('click',()=>{
  $('#signin').toggle();
  $('#signup').toggle();
})



